// 1. FOOD DATABASE
// Each item is one "row" of a nutrition table a real app would
// keep in a database. giValue = glycemic index (0-100, lower is
// better for blood sugar). diabetesFit scores each diabetes type
// from 0-10 based on established dietary guidance for that type.
// ---------------------------------------------------------------
const FOODS = [
  // ---------------- BREAKFAST · VEG ----------------
  { id:1, name:"Moong Dal Chilla with Mint Chutney", meal:["breakfast"], diet:"veg",
    serving:"2 chillas (150 g)", gi:45,
    n:{cal:210, protein:12, fat:5, carbs:28, fiber:6, sugar:3, zinc:1.6, magnesium:58, calcium:40, sodium:290, iron:2.4},
    diabetesFit:{type1:8, type2:9, gestational:8, prediabetes:9},
    ageBest:["young_adult","adult","senior"],
    benefit:"a high-protein, low-GI batter of split moong dal that digests slowly and blunts the morning glucose spike." },
  { id:2, name:"Vegetable Oats Upma", meal:["breakfast"], diet:"veg",
    serving:"1 bowl (220 g)", gi:52,
    n:{cal:230, protein:8, fat:7, carbs:34, fiber:5.5, sugar:3, zinc:1.2, magnesium:50, calcium:35, sodium:310, iron:2.0},
    diabetesFit:{type1:7, type2:8, gestational:8, prediabetes:8},
    ageBest:["young_adult","adult"],
    benefit:"whole oats and mixed vegetables that add fibre and volume without a refined-carb load." },
  { id:3, name:"Ragi (Finger Millet) Dosa with Sambar", meal:["breakfast"], diet:"veg",
    serving:"2 dosas + 1 cup sambar", gi:50,
    n:{cal:260, protein:10, fat:6, carbs:38, fiber:7, sugar:4, zinc:1.4, magnesium:75, calcium:150, sodium:340, iron:3.1},
    diabetesFit:{type1:8, type2:9, gestational:8, prediabetes:9},
    ageBest:["adult","senior"],
    benefit:"finger millet's naturally low GI and high calcium make it a favourite grain swap for steady mornings." },
  { id:4, name:"Sprouted Moong Salad Bowl", meal:["breakfast","lunch"], diet:"veg",
    serving:"1 bowl (200 g)", gi:32,
    n:{cal:180, protein:14, fat:4, carbs:22, fiber:8, sugar:4, zinc:1.8, magnesium:62, calcium:55, sodium:180, iron:2.8},
    diabetesFit:{type1:9, type2:9, gestational:9, prediabetes:9},
    ageBest:["young_adult","adult"],
    benefit:"raw sprouts keep the glycemic load very low while packing plant protein and fibre into a light start." },
  { id:5, name:"Besan (Chickpea Flour) Vegetable Uttapam", meal:["breakfast"], diet:"veg",
    serving:"2 pieces (180 g)", gi:48,
    n:{cal:220, protein:11, fat:6, carbs:30, fiber:6, sugar:3, zinc:1.5, magnesium:56, calcium:45, sodium:300, iron:2.6},
    diabetesFit:{type1:7, type2:8, gestational:8, prediabetes:8},
    ageBest:["young_adult","adult","senior"],
    benefit:"chickpea flour brings soluble fibre and protein that slow down carbohydrate absorption." },
  { id:6, name:"Greek Yogurt with Chia and Berries", meal:["breakfast"], diet:"veg",
    serving:"1 bowl (200 g)", gi:35,
    n:{cal:190, protein:16, fat:6, carbs:18, fiber:6, sugar:9, zinc:1.1, magnesium:48, calcium:210, sodium:70, iron:1.0},
    diabetesFit:{type1:8, type2:8, gestational:9, prediabetes:8},
    ageBest:["young_adult","adult"],
    benefit:"thick strained yogurt gives protein and calcium while chia slows the natural sugars in the berries." },
  { id:7, name:"Paneer Bhurji with Multigrain Roti", meal:["breakfast","dinner"], diet:"veg",
    serving:"1 roti + 100 g bhurji", gi:44,
    n:{cal:310, protein:18, fat:14, carbs:26, fiber:5, sugar:3, zinc:1.9, magnesium:52, calcium:240, sodium:320, iron:1.8},
    diabetesFit:{type1:7, type2:7, gestational:8, prediabetes:7},
    ageBest:["young_adult","adult"],
    benefit:"paneer's protein and fat slow gastric emptying, softening the blood sugar curve of the roti." },

  // ---------------- BREAKFAST · NON-VEG ----------------
  { id:8, name:"Egg White Vegetable Omelette", meal:["breakfast"], diet:"nonveg",
    serving:"3 egg whites + veg (180 g)", gi:20,
    n:{cal:180, protein:20, fat:6, carbs:8, fiber:3, sugar:3, zinc:1.3, magnesium:30, calcium:60, sodium:280, iron:1.5},
    diabetesFit:{type1:9, type2:9, gestational:8, prediabetes:9},
    ageBest:["young_adult","adult"],
    benefit:"almost pure protein with barely any carbohydrate, so it has minimal impact on post-meal glucose." },
  { id:9, name:"Boiled Eggs with Avocado on Multigrain Toast", meal:["breakfast"], diet:"nonveg",
    serving:"2 eggs + 1/2 avocado + 1 slice", gi:38,
    n:{cal:340, protein:19, fat:20, carbs:24, fiber:7, sugar:2, zinc:1.8, magnesium:60, calcium:70, sodium:260, iron:2.2},
    diabetesFit:{type1:8, type2:7, gestational:8, prediabetes:7},
    ageBest:["young_adult","adult"],
    benefit:"monounsaturated fat from avocado plus egg protein flattens the toast's carbohydrate response." },
  { id:10, name:"Grilled Chicken Sausage with Sautéed Spinach", meal:["breakfast"], diet:"nonveg",
    serving:"2 sausages + 1 cup spinach", gi:15,
    n:{cal:250, protein:24, fat:14, carbs:6, fiber:3, sugar:1, zinc:2.4, magnesium:55, calcium:80, sodium:480, iron:2.6},
    diabetesFit:{type1:8, type2:7, gestational:6, prediabetes:7},
    ageBest:["young_adult","adult"],
    benefit:"a near-zero-carb, high-protein plate — the main watch-point is its sodium content." },

  // ---------------- LUNCH · VEG ----------------
  { id:11, name:"Quinoa and Vegetable Khichdi", meal:["lunch","dinner"], diet:"veg",
    serving:"1 bowl (250 g)", gi:46,
    n:{cal:280, protein:11, fat:6, carbs:42, fiber:7, sugar:3, zinc:1.7, magnesium:80, calcium:50, sodium:300, iron:2.9},
    diabetesFit:{type1:8, type2:8, gestational:8, prediabetes:8},
    ageBest:["young_adult","adult","senior"],
    benefit:"quinoa is a complete-protein grain with a lower GI than white rice, making khichdi steadier for lunch." },
  { id:12, name:"Palak (Spinach) Dal with Brown Rice", meal:["lunch"], diet:"veg",
    serving:"1 cup dal + 3/4 cup rice", gi:50,
    n:{cal:320, protein:14, fat:6, carbs:52, fiber:9, sugar:4, zinc:2.0, magnesium:95, calcium:110, sodium:280, iron:3.6},
    diabetesFit:{type1:7, type2:8, gestational:8, prediabetes:8},
    ageBest:["adult","senior"],
    benefit:"lentils and spinach add fibre, magnesium and iron, and brown rice keeps the GI lower than polished rice." },
  { id:13, name:"Methi (Fenugreek) Thepla with Curd", meal:["lunch","breakfast"], diet:"veg",
    serving:"2 theplas + 100 g curd", gi:47,
    n:{cal:270, protein:9, fat:9, carbs:36, fiber:6, sugar:4, zinc:1.3, magnesium:52, calcium:130, sodium:310, iron:2.1},
    diabetesFit:{type1:7, type2:8, gestational:7, prediabetes:8},
    ageBest:["adult","senior"],
    benefit:"fenugreek leaves are traditionally linked to improved insulin sensitivity and add a mild, low-GI bitterness." },
  { id:14, name:"Mixed Vegetable and Chickpea Curry with Millet Roti", meal:["lunch","dinner"], diet:"veg",
    serving:"1 cup curry + 2 rotis", gi:44,
    n:{cal:340, protein:13, fat:8, carbs:50, fiber:11, sugar:5, zinc:2.1, magnesium:88, calcium:90, sodium:320, iron:3.4},
    diabetesFit:{type1:8, type2:9, gestational:8, prediabetes:9},
    ageBest:["young_adult","adult"],
    benefit:"chickpeas plus millet roti deliver one of the highest fibre loads in the menu, which slows carb absorption." },
  { id:15, name:"Bottle Gourd (Lauki) Dal with Bajra Roti", meal:["lunch","dinner"], diet:"veg",
    serving:"1 cup dal + 2 rotis", gi:42,
    n:{cal:290, protein:10, fat:6, carbs:44, fiber:8, sugar:3, zinc:1.6, magnesium:70, calcium:65, sodium:270, iron:2.5},
    diabetesFit:{type1:7, type2:8, gestational:8, prediabetes:8},
    ageBest:["senior","adult"],
    benefit:"a light, high-water-content vegetable dal with pearl millet roti — easy to digest for older adults." },
  { id:16, name:"Rajma (Kidney Bean) Curry with Quinoa", meal:["lunch"], diet:"veg",
    serving:"1 cup curry + 3/4 cup quinoa", gi:45,
    n:{cal:350, protein:16, fat:7, carbs:53, fiber:12, sugar:4, zinc:2.3, magnesium:92, calcium:80, sodium:300, iron:3.8},
    diabetesFit:{type1:8, type2:8, gestational:7, prediabetes:8},
    ageBest:["young_adult","adult"],
    benefit:"kidney beans are a classic low-GI legume, and quinoa in place of white rice keeps the whole plate slower-burning." },

  // ---------------- LUNCH · NON-VEG ----------------
  { id:17, name:"Grilled Fish Curry with Brown Rice", meal:["lunch","dinner"], diet:"nonveg",
    serving:"150 g fish + 3/4 cup rice", gi:48,
    n:{cal:360, protein:28, fat:12, carbs:38, fiber:4, sugar:3, zinc:1.4, magnesium:60, calcium:50, sodium:340, iron:1.6},
    diabetesFit:{type1:8, type2:8, gestational:8, prediabetes:8},
    ageBest:["young_adult","adult","senior"],
    benefit:"omega-3-rich fish protein pairs with brown rice for a moderate, well-rounded glycemic response." },
  { id:18, name:"Tandoori Chicken with Sautéed Greens", meal:["lunch","dinner"], diet:"nonveg",
    serving:"150 g chicken + 1 cup greens", gi:18,
    n:{cal:300, protein:32, fat:14, carbs:8, fiber:4, sugar:2, zinc:2.6, magnesium:58, calcium:70, sodium:420, iron:2.0},
    diabetesFit:{type1:9, type2:8, gestational:6, prediabetes:8},
    ageBest:["young_adult","adult"],
    benefit:"very low carbohydrate and high protein, so it barely moves blood sugar — watch the marinade's salt." },
  { id:19, name:"Chicken Stew with Root Vegetables", meal:["lunch","dinner"], diet:"nonveg",
    serving:"1 bowl (300 g)", gi:40,
    n:{cal:280, protein:24, fat:9, carbs:26, fiber:5, sugar:5, zinc:2.2, magnesium:50, calcium:55, sodium:380, iron:1.9},
    diabetesFit:{type1:8, type2:7, gestational:8, prediabetes:7},
    ageBest:["senior","adult"],
    benefit:"a gently cooked, well-tolerated stew — a good option when digestion needs to be easy, as in later pregnancy." },
  { id:20, name:"Egg Curry with Multigrain Roti", meal:["lunch","dinner"], diet:"nonveg",
    serving:"2 eggs curry + 2 rotis", gi:46,
    n:{cal:340, protein:20, fat:16, carbs:32, fiber:6, sugar:3, zinc:1.9, magnesium:54, calcium:90, sodium:360, iron:2.7},
    diabetesFit:{type1:7, type2:7, gestational:6, prediabetes:7},
    ageBest:["young_adult","adult"],
    benefit:"egg protein and fat moderate the roti's carbohydrate release for a steadier lunch curve." },

  // ---------------- DINNER · VEG ----------------
  { id:21, name:"Vegetable Soup with Lentil Dumplings", meal:["dinner"], diet:"veg",
    serving:"1 bowl (300 ml)", gi:30,
    n:{cal:170, protein:9, fat:3, carbs:26, fiber:6, sugar:4, zinc:1.2, magnesium:48, calcium:40, sodium:360, iron:1.9},
    diabetesFit:{type1:8, type2:9, gestational:8, prediabetes:9},
    ageBest:["senior","adult"],
    benefit:"a light, low-calorie evening bowl with lentil dumplings for protein — gentle on digestion before bed." },
  { id:22, name:"Stir-Fried Tofu and Vegetables", meal:["dinner","lunch"], diet:"veg",
    serving:"1 plate (250 g)", gi:25,
    n:{cal:220, protein:16, fat:10, carbs:16, fiber:5, sugar:5, zinc:1.8, magnesium:65, calcium:180, sodium:390, iron:2.4},
    diabetesFit:{type1:9, type2:9, gestational:8, prediabetes:9},
    ageBest:["young_adult","adult"],
    benefit:"tofu keeps carbs low while adding calcium and complete plant protein for the evening meal." },
  { id:23, name:"Cabbage and Moong Dal Stir Fry", meal:["dinner"], diet:"veg",
    serving:"1 bowl (200 g)", gi:33,
    n:{cal:190, protein:10, fat:5, carbs:24, fiber:7, sugar:3, zinc:1.5, magnesium:56, calcium:60, sodium:250, iron:2.2},
    diabetesFit:{type1:8, type2:9, gestational:8, prediabetes:9},
    ageBest:["senior","adult"],
    benefit:"a simple, high-fibre stir fry that's light enough for a late meal without spiking sugar overnight." },
  { id:24, name:"Bhindi (Okra) Sabzi with Jowar Roti", meal:["dinner","lunch"], diet:"veg",
    serving:"1 cup sabzi + 2 rotis", gi:41,
    n:{cal:260, protein:8, fat:7, carbs:40, fiber:8, sugar:3, zinc:1.4, magnesium:70, calcium:70, sodium:270, iron:2.3},
    diabetesFit:{type1:7, type2:8, gestational:8, prediabetes:8},
    ageBest:["adult","senior"],
    benefit:"okra's natural mucilage and sorghum roti together give a slower, steadier carbohydrate release." },
  { id:25, name:"Mushroom and Spinach Curry with Cauliflower Rice", meal:["dinner"], diet:"veg",
    serving:"1 bowl (280 g)", gi:22,
    n:{cal:190, protein:9, fat:8, carbs:16, fiber:6, sugar:4, zinc:1.6, magnesium:60, calcium:75, sodium:300, iron:2.0},
    diabetesFit:{type1:9, type2:9, gestational:8, prediabetes:9},
    ageBest:["young_adult","adult"],
    benefit:"swapping rice for cauliflower keeps this dinner very low-carb while mushrooms add zinc and B-vitamins." },

  // ---------------- DINNER · NON-VEG ----------------
  { id:26, name:"Grilled Salmon with Steamed Broccoli", meal:["dinner"], diet:"nonveg",
    serving:"150 g salmon + 1 cup broccoli", gi:12,
    n:{cal:320, protein:30, fat:18, carbs:8, fiber:4, sugar:2, zinc:1.3, magnesium:52, calcium:60, sodium:220, iron:1.4},
    diabetesFit:{type1:9, type2:9, gestational:8, prediabetes:9},
    ageBest:["young_adult","adult","senior"],
    benefit:"omega-3 fats and near-zero carbohydrate make this one of the steadiest dinners on the menu." },
  { id:27, name:"Chicken Clear Soup with Vegetables", meal:["dinner"], diet:"nonveg",
    serving:"1 bowl (300 ml)", gi:15,
    n:{cal:150, protein:18, fat:4, carbs:10, fiber:3, sugar:2, zinc:1.5, magnesium:35, calcium:30, sodium:420, iron:1.2},
    diabetesFit:{type1:8, type2:8, gestational:7, prediabetes:8},
    ageBest:["senior","adult"],
    benefit:"a light, warming, low-carb broth that's easy on digestion for a late dinner." },
  { id:28, name:"Baked Fish with Sautéed Greens", meal:["dinner"], diet:"nonveg",
    serving:"150 g fish + 1 cup greens", gi:14,
    n:{cal:260, protein:29, fat:11, carbs:7, fiber:4, sugar:2, zinc:1.2, magnesium:48, calcium:65, sodium:260, iron:1.5},
    diabetesFit:{type1:9, type2:8, gestational:8, prediabetes:8},
    ageBest:["adult","senior"],
    benefit:"lean, baked (not fried) preparation keeps saturated fat down while protein stays high." },
  { id:29, name:"Egg Drop Vegetable Soup", meal:["dinner"], diet:"nonveg",
    serving:"1 bowl (300 ml)", gi:20,
    n:{cal:160, protein:12, fat:6, carbs:12, fiber:3, sugar:2, zinc:1.1, magnesium:32, calcium:40, sodium:400, iron:1.3},
    diabetesFit:{type1:8, type2:8, gestational:6, prediabetes:8},
    ageBest:["senior","adult"],
    benefit:"a fast, low-carb evening bowl — light enough not to disturb overnight glucose." },
];

// ---------------------------------------------------------------
